### PR TITLE
Skip extra-files-dir config if it doesn't exist

### LINKED ISSUE #54: `tailon -c` fails if `extra-files-dir` doesn't exit
```
$ tailon -v
tailon version 1.4.1

$ tailonc -c config.yml

Traceback (most recent call last):
  File "/usr/local/bin/tailon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tailon/main.py", line 282, in main
    config = setup(opts)
  File "/usr/local/lib/python2.7/dist-packages/tailon/main.py", line 213, in setup
    config = parseconfig(opts.config)
  File "/usr/local/lib/python2.7/dist-packages/tailon/main.py", line 81, in parseconfig
    for file in os.listdir(config['extra-files-dir']):
OSError: [Errno 2] No such file or directory: '/etc/tailon/files.d/'

$ mkdir -p /etc/tailon/files.d
$ tailonc -c config.yml

[+61.144829][ INFO] Listening on 0.0.0.0:8080
```

### PR DESCRIPTION
**Pull request by petehalverson**
Fixes #54

### CODE REVIEW

**Comment by gvalkov** [comment]
Thanks for the fix. I must admit I took the `extra-files-dir` PR in rather blindly.

**Comment by petehalverson** [comment]
No problem! Thanks for pulling it in so quickly

Will that update automatically trickle down to [PIP](http://pypi.python.org/pypi/tailon)?

**Comment by gvalkov** [comment]
Sorry, I've been seriously neglecting my open-source projects lately. Just pushed 1.4.2 to pypi with your fix. Thanks again.

**Comment by petehalverson** [comment]
No need to apologize! Thanks for posting that.

**Pull request merged**
